version: 2.1
general:

jobs:

  build:

    working_directory: ~/repo

    docker:
    - image: circleci/openjdk:8-jdk

    environment:
      # Customize the JVM maximum heap size
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout
      
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # use latest cache if no exact match found
            - v1-dependencies-
      
    #  - run:
    #      name: create package
    #      command: mvn clean install -Dmaven.test.skip=true
          
      - save_cache:
          key: v1-dependencies-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2
            
      #- run:
      #    name: save package to an archive
      #    command: |
      #      mkdir -p archive/target
      #      pwd
      #      ls -lart ~/repo/target
      #      cp -r ~/repo/target/*.jar ~/repo/archive/target/
            
    #  - persist_to_workspace:
    #      root: .
    #      paths:
    #        - archive
            
      - run:
          name: spark submit
          command: |
             ssh ec2-user@52.90.58.147
             spark-submit \
             --master spark://52.90.58.147:7077,3.88.224.41:7077 \
             --class org.apache.spark.examples.SparkPi /usr/local/spark/examples/jars/spark-examples_2.11-2.4.3.jar
